### ISSUE TITLE
Add composer.json since you've been removed from wordpress repo

### ISSUE THREAD

**Issue by jonathan-dejong** [clerkio/clerk-woocommerce#11]
Hi! 

Since you guys have been removed from WordPress SVN due to guideline violations it's no longer possible to handle the plugin using wpackagist.org.

This could be sort of "resolved" if you add a composer.json file to this repo. That way we could pull the versions from github instead :) 

I believe this is kinda what you need to add (with proper values).
```json
{
	"name": "",
	"description": "",
	"keywords": ["WordPress"],
	"homepage": "",
	"authors": [
	],
	"type": "wordpress-plugin",
	"repositories": [
		{
			"type": "composer",
			"url": "https://wpackagist.org"
		}
	]
}

```

**Comment by Wesso** [comment]
Sorry for the delay.

It is added and will be available in the next release.
