### ISSUE TITLE
Support for WP >5.5 rest route definitions

### ISSUE THREAD

**Issue by rasmustaarnby** [clerkio/clerk-woocommerce#12]
WordPress >5.5 requires the rest route definitions to include the permission callback in the arguments. 

Should be updated in the flowing file https://github.com/clerkio/clerk-woocommerce/blob/master/includes/class-clerk-rest-api.php#L43-L88

If the endpoints are intended to be public you can add it like this: `'permission_callback' => '__return_true',` 

Eg.: 
```
register_rest_route('clerk', '/product', [
	'methods' => 'GET',
	'callback' => [$this, 'product_endpoint_callback'],
	'permission_callback' => '__return_true',
]);
```

**Comment by Dekadinious** [comment]
It's incredible how stuck support is on this. Not even answering here! It's been over a year...

**Comment by Wesso** [comment]
Sorry for the delay.

This is fixed and ready in the next release

**Comment by Dekadinious** [comment]
@Wesso Thanks, better late than never :)
