### ISSUE TITLE
Styles and scripts enqueued too early

### ISSUE THREAD

**Issue by rasmustaarnby** [clerkio/clerk-woocommerce#4]
The plugin seems to enqueue `wp-jquery-ui-dialog` and `jquery-ui-dialog` incorrectly and produces a few notices and warnings in the admin panel. 

The error seems to originate from https://github.com/clerkio/clerk-woocommerce/blob/master/includes/class-clerk-admin-settings.php#L37-L38

Scripts and styles should not be registered or enqueued until the `wp_enqueue_scripts` https://developer.wordpress.org/reference/hooks/wp_enqueue_scripts/

![Skærmbillede 2020-02-04 kl  12 55 51](https://user-images.githubusercontent.com/477220/73742909-bbfa0500-474d-11ea-8452-14e62d2c4d0c.png)
![Skærmbillede 2020-02-04 kl  12 56 04](https://user-images.githubusercontent.com/477220/73742910-bbfa0500-474d-11ea-86d2-ba38bf2a817b.png)

**Comment by CasperKN** [comment]
Hey Rasmus,
Thanks for your time and feedback, i have released a fix for it now :)
