### ISSUE TITLE
class-clerk-product-sync causes fatal error when saving posts

### ISSUE THREAD

**Issue by badwulfx** [clerkio/clerk-woocommerce#44]
Hi devs, we've encountered a problem where, when saving a post, the class-clerk-products-sync.php file returns a fatal error:

```
Fatal error: Uncaught Error: array_values(): Argument #1 ($array) must be of type array, null given
in /www/elementorbuild_752/public/wp-content/plugins/clerk-woocommerce-master/includes/class-clerk-product-sync.php on line 197

Oproepstack:

array_values()
wp-content/plugins/clerk-woocommerce-master/includes/class-clerk-product-sync.php:197
Clerk_Product_Sync::add_product()
wp-content/plugins/clerk-woocommerce-master/includes/class-clerk-product-sync.php:73
Clerk_Product_Sync::save_product()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-includes/post.php:4673
wp_insert_post()
wp-includes/post.php:4775
wp_update_post()
wp-admin/includes/post.php:426
edit_post()
wp-admin/post.php:227
```

Our fix was this on line 197:
`$options_array = array_values($variation['attributes'] ?? []);`
Adding `?? []` fixed the error.

Can you please include this in the next update?

**Comment by FoulBachelor** [comment]
Hi CodeWulf,

Thanks for bringing this to my attention. I have guarded it slightly differently from your suggestion, but it will be included in the next update.

https://github.com/clerkio/clerk-woocommerce/commit/fc2bd1453dd862e8d3d3b1c378e6083b07d2302f
