### ISSUE TITLE
A lot of notices from undefined index in options

### ISSUE THREAD

**Issue by rasmustaarnby** [clerkio/clerk-woocommerce#6]
The plugin generetes excessive amounts of undefined index notices from trying to access options that does not exist. A solution could be to either check if the index is set or provide defaults.

I have added a log file, with the notices from just one page load in the settings page. 

[clerkio.log](https://github.com/clerkio/clerk-woocommerce/files/4219476/clerkio.log)

**Comment by Wesso** [comment]
These are fixed in later releases after the issue date.
