### ISSUE TITLE
Unable to remove a product

### ISSUE THREAD

**Issue by rafal-sokolowski** [clerkio/clerk-woocommerce#62]
`Clerk_Api::remove_product` doesn't remove products.

Steps to reproduce:
Change a product status to draft and save.

The problem is that `http_build_query( $params )` function used in `wp-content/plugins/clerkio/includes/class-clerk-api.php:165` creates array indexes for parameters (e.g. `products[0]`) which are not supported by the Clerk.io API.

In other words, this call:
`https://api.clerk.io/v2/product/remove?key=XXX&private_key=XXX&products[0]=1234567890`
will return a parsing error "Missing argument: products".

Whereas, this one:
`https://api.clerk.io/v2/product/remove?key=XXX&private_key=XXX&products[]=1234567890`
will work fine.

**Comment by Dekadinious** [comment]
@stubbedev I just saw this and wanted to ping you if you haven't already seen it :)

**Comment by stubbedev** [comment]
@Dekadinious looking now :+1:

**Comment by stubbedev** [comment]
@Dekadinious It should be resolved with this: https://github.com/clerkio/clerk-woocommerce/commit/923c0e5bd134b845802390c82a3fd80eac88d89e

Thanks for pinging me. :heart:
