### ISSUE TITLE
Setting add_option with incorrect key

### ISSUE THREAD

**Issue by rasmustaarnby** [clerkio/clerk-woocommerce#8]
In class-clerk-admin-settings.php there are some add_option's where the old/saved clerk_options is used as the key, this does not make sense. I'm guessing it should be the key `clerk_options` and not the array of options itself. 

See
https://github.com/clerkio/clerk-woocommerce/blob/master/includes/class-clerk-admin-settings.php#L56
https://github.com/clerkio/clerk-woocommerce/blob/master/includes/class-clerk-admin-settings.php#L66
https://github.com/clerkio/clerk-woocommerce/blob/master/includes/class-clerk-admin-settings.php#L76

Stack trace:

```
( ! ) Warning: trim() expects parameter 1 to be string, array given in /public/wp/wp-includes/option.php on line 469
--
1 | 0.0002 | 412744 | {main}( ) | .../plugins.php:0
2 | 0.0002 | 413128 | require_once( '/public/wp/wp-admin/network/admin.php' ) | .../plugins.php:11
3 | 0.0002 | 414400 | require_once( '/public/wp/wp-admin/admin.php' ) | .../admin.php:13
4 | 0.0002 | 414992 | require_once( '/public/wp/wp-load.php' ) | .../admin.php:34
5 | 0.0003 | 416096 | require_once( '/public/wp-config.php' ) | .../wp-load.php:42
6 | 0.0015 | 451144 | require_once( '/public/wp/wp-settings.php' ) | .../wp-config.php:188
7 | 0.0172 | 2618064 | include_once( '/public/wp-content/plugins/clerk-woocommerce-3.0.0/clerk.php' ) | .../wp-settings.php:309
8 | 0.0172 | 2618480 | Clerk->__construct( ) | .../clerk.php:69
9 | 0.0172 | 2618480 | Clerk->includes( ) | .../clerk.php:23
10 | 0.0176 | 2687168 | require_once( '/public/wp-content/plugins/clerk-woocommerce-3.0.0/includes/class-clerk-admin-settings.php' ) | .../clerk.php:33
11 | 0.0176 | 2687248 | Clerk_Admin_Settings->__construct( ) | .../class-clerk-admin-settings.php:2037
12 | 0.0177 | 2693056 | Clerk_Admin_Settings->InitializeSettings( ) | .../class-clerk-admin-settings.php:25
13 | 0.0183 | 2695256 | add_option( ) | .../class-clerk-admin-settings.php:72
14 | 0.0184 | 2695256 | trim ( ) | .../option.php:469
```

**Comment by Wesso** [comment]
I read thoroughly your suggestion, but it is correct as it is set up and it is meant to be as is.

The options you talk about is for initialization purpose and to perform an evaluation in the code:
- livesearch_initiated
- powerstep_initiated
- search_initiated
- exit_intent_initiated
- category_initiated
- product_initiated
- cart_initiated
- sync_mails_initiated
- disable_order_sync_initiated

Thanks for your remark
