### ISSUE TITLE
Logger sets user agent on every single page load

### ISSUE THREAD

**Issue by rasmustaarnby** [clerkio/clerk-woocommerce#9]
The logger is setting the user-agent on all page loads. I guess this should only be sent to whatever logging system you're using but right now it's exposing server and php version. 

https://github.com/clerkio/clerk-woocommerce/blob/master/includes/class-clerk-logger.php#L45

**Comment by Wesso** [comment]
Thank you for being aware of that.

This was fixed in release 3.1.0 on 26 of March 2020
